#!/usr/bin/env ruby
require "rubygems"
require "bundler/setup"
require "mailman"

Mailman.config.logger = Logger.new("log/mailman.log")



Mailman.config.pop3 = {
  :username => '',
  :password => '',
  :server   => '',
}

Mailman.config.poll_interval = 10

Mailman::Application.run do
  default do
    begin
    	puts "Received: #{message.subject} - #{message.body.decoded}" 
      Ticket.receive_mail(message)
    rescue Exception => e
      Mailman.logger.error "Exception occurred while receiving message:\n#{message}"
      Mailman.logger.error [e, *e.backtrace].join("\n")
    end
  end
end